# check email is available

GET http://localhost/api/u/check/email/basic@examples.com

###

# check nickname is available


GET http://localhost/api/u/check/nickname/BasicAPIBot

###

# get captcha for a request

GET  http://localhost/api/captcha?dev=true

###

# register. use the cookie and captcha got from above.

POST http://localhost/api/u/register?dev=true
Content-Type: application/json
Cookie: oj.sid=s%3AcuqUZvaSwYCAx4SacLfg8NMPdD-72j1Y.vRGd5euPAbG6emn5UW2TWt2tEfyUPTt4kuRmgdJe8jc;

{
  "nickname": "BasicAPIBot",
  "password": "plainOrEncrypted",
  "email": "basic@examples.com",
  "school": "南开大学",
  "gender": 1,
  "captcha": "77Z8h8"
}

###

# get an api key and name it 'API Test', must use cookie above

PUT http://localhost/api/u/api/apply/API%20Test
Cookie: oj.sid=s%3AkkyQjR5JJDJUpxmEpfRSUZReKiq9S-ul.tV4Ki7yFfcaVvYj7ER0RJMLfkYjnabvnrkAPRXbWT80;

###

# get info of self

GET http://localhost/api/u/info
Authorization: Negotiate 0a6660c8c8d1 e54282404214a0818f602d63

###

# get info of some another

GET http://localhost/api/u/info/sunrisefox
Authorization: Negotiate 0a6660c8c8d1 e54282404214a0818f602d63

###

# get all sessions

GET http://localhost/api/u/session
Authorization: Negotiate 0a6660c8c8d1 e54282404214a0818f602d63

###

# !!! logout (not work for api)

DELETE http://localhost/api/u/logout
Cookie: oj.sid=s%3ARbW-oZVY-QmmSG9FaXSZj82uzaxu1hf7.D36Nm9E4%2Fs0MifSG32whApsTet0GrfroMIjQSSIFZ78; Path=/; Expires=Mon, 01 Oct 2018 23:35:38 GMT; HttpOnly

###

# logout all login of current user (!!! invalidate all cookies of the user)

DELETE http://localhost/api/u/logout/force
Authorization: Negotiate 60342b2358c2 48aeb548443d42f441b266b9

###

# !!! login (not work for api)

POST http://localhost/api/u/login?dev=true
Content-Type: application/json
Cookie: oj.sid=s%3ARbW-oZVY-QmmSG9FaXSZj82uzaxu1hf7.D36Nm9E4%2Fs0MifSG32whApsTet0GrfroMIjQSSIFZ78; Path=/; Expires=Mon, 01 Oct 2018 23:35:38 GMT; HttpOnly

{
  "user":"basic",
  "password": "plainOrEncrypted",
  "captcha": "rihaLZ"
}

###

# update info
# avatar is not tested..

POST http://localhost/api/u/update?dev=true
Content-Type: application/json
Authorization: Negotiate 60342b2358c2 48aeb548443d42f441b266b9

{
  "nickname": "basic",
  "email": "445400747@qq.com",
  "gender": 2,
  "qq": "10000",
  "phone": "18888888888",
  "real_name": "jhsSDF",
  "school": "jhsSDF",
  "password": "plainOrEncrypted",
  "words": "jhsSDF"
}

###

# send verification email

GET http://localhost/api/u/verify/send
Authorization: Negotiate 60342b2358c2 48aeb548443d42f441b266b9

###

# check if user send register email

GET http://localhost/api/u/verify/fetch?subject=Verified
Authorization: Negotiate 0a6660c8c8d1 e54282404214a0818f602d63

###

# verify email

GET http://localhost/api/u/verify/email?hash=<hash>&code=<code>

####

# list user apis

GET http://localhost/api/u/api
Authorization: Negotiate 0a6660c8c8d1 e54282404214a0818f602d63

###

# add an api key and name it 'Office PC'

PUT http://localhost/api/u/api/apply/Office%20PC
Authorization: Negotiate 60342b2358c2 48aeb548443d42f441b266b9

###

# add an api key and name it 'Office PC Very Very Long Name'

PUT http://localhost/api/u/api/apply/Office%20PC%20Very%20Very%20Long%20Name
Authorization: Negotiate 60342b2358c2 48aeb548443d42f441b266b9

###

# disable an api key 60342b2358c2

PUT http://localhost/api/u/api/disable/60342b2358c2
Authorization: Negotiate 0a6660c8c8d1 e54282404214a0818f602d63

###

# enable an api key 60342b2358c2

PUT http://localhost/api/u/api/enable/60342b2358c2
Authorization: Negotiate 0a6660c8c8d1 e54282404214a0818f602d63

###

# delete an api key 60342b2358c2

DELETE http://localhost/api/u/api/60342b2358c2
Authorization: Negotiate 0a6660c8c8d1 e54282404214a0818f602d63

###

# delete an api key 6d6653c07775 / PUT method

PUT http://localhost/api/u/api/delete/6d6653c07775
Authorization: Negotiate 0a6660c8c8d1 e54282404214a0818f602d63

###
# rename an api key 0a6660c8c8d1 to PC Office

PUT http://localhost/api/u/api/rename/0a6660c8c8d1/PC%20Office
Authorization: Negotiate 0a6660c8c8d1 e54282404214a0818f602d63

###
